spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/customerDb
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: ${PORT:8081}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html